### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by chennakesava89**
please review my code

### CODE REVIEW

**Review by harisri9948 — APPROVED** [review]
I don't have your source code for JSON file  to run your program I hope it's working fine

**Review by Rajkumar-V — APPROVED** [review]
Define a function to read the data from the file

**Comment by Jsm-mani** [comment]
good but please mention logic in a function

**Review by Jsm-mani — APPROVED** [review]
good but please mention the logic in a function

**Review by amlya1230 — CHANGES_REQUESTED** [review]
Please re-implement the code with classes and functions

**Pull request closed without merging**
